version: '3.3'
services:
  mypostgres:
    image: postgres:11.4-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    container_name: app
    restart: on-failure
    ports:
      - 8090:8090
    depends_on:
      - mypostgres